version = 1

[[annotations]]
path = [
    ".editorconfig",
    ".gitignore",
    "flake.lock",
    "flake.nix",
    "hosts/**",
    "installer/**",
    "nix/**",
    "treefmt.nix",
]
SPDX-FileCopyrightText = "Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"
